namespace: "prod-public-catalog"
techStack: "nodejs"

deployment:
  replicas: 1
  env:
    LOG_LEVEL: "info"
  image:
    repositoryPrefix: "697818730278.dkr.ecr.eu-south-1.amazonaws.com"
    imagePullPolicy: Always
    tag: $IMAGE_TAG_PLACEHOLDER
    digest: $IMAGE_DIGEST_PLACEHOLDER
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

local:
  interop_public_catalog_commons:
    AWS_ACCOUNT_ID: "697818730278"