apiVersion: v1
kind: ConfigMap
metadata:
  name: common-read-model-sql
  namespace: prod-public-catalog
data:
  DB_HOST_RO: "interop-platform-data-prod.cluster-ro-cgo3fcsduspu.eu-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "read_model"
  DB_USE_SSL: "true"
  DB_SCHEMA_AGREEMENT: "prod_agreement"
  DB_SCHEMA_ATTRIBUTE_REGISTRY: "prod_attribute_registry"
  DB_SCHEMA_AUTHORIZATION: "prod_authorization"
  DB_SCHEMA_CATALOG: "prod_catalog"
  DB_SCHEMA_DELEGATION: "prod_delegation"
  DB_SCHEMA_ESERVICE_TEMPLATE: "prod_eservice_template"
  DB_SCHEMA_NOTIFICATION_CONFIG: "prod_notification_config"
  DB_SCHEMA_NOTIFICATION_EVENT: "prod_notification_event"
  DB_SCHEMA_PURPOSE: "prod_purpose"
  DB_SCHEMA_PURPOSE_TEMPLATE: "prod_purpose_template"
  DB_SCHEMA_TENANT: "prod_tenant"
