name: "interop-public-catalog-strapi"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.interop_public_catalog_commons.AWS_ACCOUNT_ID}}:role/interop-public-catalog-strapi-dev"

service:
  create: true
  portName: http
  containerPort: 8080

configmap:
  AWS_BUCKET: "interop-public-catalog-cms-assets-dev-es1"
  CDN_ID: "E2V4OXZKWZ5U4B"
  CDN_INVALIDATION_PATH: "/news/*"
  GH_WORKFLOW_OWNER: "pagopa"
  GH_WORKFLOW_REPO: "interop-public-catalog-deployment"
  GH_WORKFLOW_ID: "invalidate-cache.yaml"

deployment:
  envFromConfigmaps:
    DATABASE_CLIENT: "postgres"
    DATABASE_HOST: "common-public-catalog-data-sql.DB_HOST_RO"
    DATABASE_PORT: "common-public-catalog-data-sql.DB_PORT"
    DATABASE_NAME: "common-public-catalog-data-sql.DB_NAME"
    DATABASE_SSL: "common-public-catalog-data-sql.DB_USE_SSL"
    DATABASE_SCHEMA: "common-public-catalog-data-sql.DB_SCHEMA_STRAPI"
  envFromSecrets:
    DATABASE_USERNAME: "public-catalog-data-strapi-user.username"
    DATABASE_PASSWORD: "public-catalog-data-strapi-user.password"
    APP_KEYS: 
    API_TOKEN_SALT:
    ENCRYPTION_KEY:
    ADMIN_JWT_SECRET:
    JWT_SECRET:
    GH_WORKFLOW_TOKEN: