name: "strapi"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-public-catalog-strapi-dev"

service:
  create: true
  portName: http
  containerPort: 8080

configmap:
  AWS_BUCKET: "arn:aws:s3:::interop-public-catalog-cms-assets-dev-es1"

deployment:
  envFromConfigmaps:
    DATABASE_HOST: "common-public-catalog-data-sql.DB_HOST_RO"
    DATABASE_PORT: "common-public-catalog-data-sql.DB_PORT"
    DATABASE_NAME: "common-public-catalog-data-sql.DB_NAME"
    DATABASE_SSL: "common-public-catalog-data-sql.DB_USE_SSL"
  envFromSecrets:
    DATABASE_USERNAME: "public-catalog-data-strapi-user.username"
    DATABASE_PASSWORD: "public-catalog-data-strapi-user.password"