name: "interop-public-catalog-astro-frontend"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/interop-public-catalog-astro-frontend-prod"

service:
  create: true
  portName: http
  containerPort: 8080
  targetGroupArn: "arn:aws:elasticloadbalancing:eu-south-1:{{.Values.local.awsAccountId}}:targetgroup/prod-public-catalog-astro/..." #TBD
  targetType: "ip"
  ipAddressType: "ipv4"

configmap:
  STRAPI_API_ENDPOINT: "http://strapi.{{.Values.namespace}}:8080"

deployment:
  flywayInitContainer:
    create: true
    version: "11.4.0"
    downloadRedshiftDriver: false
    migrationsConfigmap: "flyway-public-catalog"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "prod"
      FLYWAY_URL: jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)
      FLYWAY_SCHEMAS: "{{.Values.local.env}}_catalog" # Necessary to define the schema in which Flyway will create the flyway_schema_history table
    envFromConfigmaps:
      DB_HOST: "common-public-catalog-data.DB_HOST"
      DB_PORT: "common-public-catalog-data.DB_PORT"
      DB_NAME: "common-public-catalog-data.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "public-catalog-data-flyway-user.username"
      FLYWAY_PASSWORD: "public-catalog-data-flyway-user.password"

  env:
    HOST: "0.0.0.0"
    PORT: "8080"
  envFromConfigmaps:
    PUBLICMODEL_SQL_DB_HOST: "common-public-catalog-data.DB_HOST_RO"
    PUBLICMODEL_SQL_DB_PORT: "common-public-catalog-data.DB_PORT"
    PUBLICMODEL_SQL_DB_NAME: "common-public-catalog-data.DB_NAME"
    PUBLICMODEL_SQL_DB_USE_SSL: "common-public-catalog-data.DB_USE_SSL"
    PUBLICMODEL_SQL_DB_SCHEMA_TENANT: "common-public-catalog-data.DB_SCHEMA_TENANT"
    PUBLICMODEL_SQL_DB_SCHEMA_CATALOG: "common-public-catalog-data.DB_SCHEMA_CATALOG"
    PUBLICMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-public-catalog-data.DB_SCHEMA_ATTRIBUTE"
  envFromSecrets:
    PUBLICMODEL_SQL_DB_USERNAME: "public-catalog-data-astro-frontend-user.username"
    PUBLICMODEL_SQL_DB_PASSWORD: "public-catalog-data-astro-frontend-user.password"
    STRAPI_API_TOKEN: "public-catalog-astro-frontend-strapi-api-token.value"

  livenessProbe:
    httpGet:
      path: /api/status
      port: http
    initialDelaySeconds: 15
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: /api/status
      port: http
    initialDelaySeconds: 15
    periodSeconds: 5
