name: "astro-frontend"

serviceAccount:
  roleArn: "arn:aws:iam::697818730278:role/..." #TBD

service:
  create: true
  portName: http
  containerPort: 8080
  targetGroupArn: "arn:aws:elasticloadbalancing:eu-south-1:697818730278:targetgroup/prod-public-catalog-astro/..." #TBD
  targetType: "ip"
  ipAddressType: "ipv4"

configmap:

deployment:
  env:
  envFromConfigmaps:
    DB_HOST: "common-public-catalog-data-sql.DB_HOST_RO"
    DB_PORT: "common-public-catalog-data-sql.DB_PORT"
    DB_NAME: "common-public-catalog-data-sql.DB_NAME"
    DB_USE_SSL: "common-public-catalog-data-sql.DB_USE_SSL"
  envFromSecrets:
    DB_USERNAME: "public-catalog-data-astro-frontend-user.username"
    DB_PASSWORD: "public-catalog-data-astro-frontend-user.password"