name: "astro-frontend"

serviceAccount:
  roleArn: "arn:aws:iam::697818730278:role/..." #TBD

service:
  create: true
  portName: http
  containerPort: 8080
  targetGroupArn: "arn:aws:elasticloadbalancing:eu-south-1:697818730278:targetgroup/prod-public-catalog-astro/..." #TBD
  targetType: "ip"
  ipAddressType: "ipv4"

configmap:

deployment:
  env:
  envFromConfigmaps:
    DB_HOST: "common-...DB_HOST"
    DB_NAME: "ccommon-...DB_NAME"
    DB_PORT: "common-...DB_PORT"
    DB_USE_SSL: "common-...DB_USE_SSL"
  envFromSecrets:
    DB_USERNAME: ""
    DB_PASSWORD: ""