apiVersion: v2
name: interop-public-catalog-deployment
description: Interop Public Catalog
type: application
version: 0.0.1
dependencies:
  - name: interop-eks-microservice-chart
    version: 1.33.0
    repository: "https://pagopa.github.io/interop-eks-microservice-chart"
  - name: interop-eks-cronjob-chart
    version: 1.9.0
    repository: "https://pagopa.github.io/interop-eks-cronjob-chart"
