name: "public-catalog-updater"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.interop_public_catalog_commons.AWS_ACCOUNT_ID}}:role/interop-public-catalog-updater-prod"

cronjob:
  schedule: "0 20 * * *"
  timeZone: "Europe/Rome"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 1
  restartPolicy: OnFailure

  envFromConfigmaps:
    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"
    PUBLIC_CATALOG_DATA_SQL_DB_HOST: "common-public-catalog-data-sql.DB_HOST_RO"
    PUBLIC_CATALOG_DATA_SQL_DB_PORT: "common-public-catalog-data-sql.DB_PORT"
    PUBLIC_CATALOG_DATA_SQL_DB_NAME: "common-public-catalog-data-sql.DB_NAME"
    PUBLIC_CATALOG_DATA_SQL_DB_USE_SSL: "common-public-catalog-data-sql.DB_USE_SSL"

  envFromSecrets:
    READMODEL_SQL_DB_USERNAME: "platform-data-public-catalog-updater-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-public-catalog-updater-user.password"
    PUBLIC_CATALOG_DATA_SQL_DB_USERNAME: "public-catalog-data-public-catalog-updater-user.username"
    PUBLIC_CATALOG_DATA_SQL_DB_PASSWORD: "public-catalog-data-public-catalog-updater-user.password"
