name: "interop-public-catalog-updater"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/interop-public-catalog-updater-prod"

configmap:
  CDN_ID: "" #TBD
  CDN_INVALIDATION_PATH: "/catalogo/*" #TBD

cronjob:
  schedule: "0 20 * * *"
  timeZone: "Europe/Rome"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 1
  restartPolicy: OnFailure

  flywayInitContainer:
    create: true
    version: "11.4.0"
    downloadRedshiftDriver: false
    migrationsConfigmap: "flyway-public-catalog"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "prod"
      FLYWAY_URL: jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)
      FLYWAY_SCHEMAS: "{{.Values.local.env}}_catalog" # Necessary to define the schema in which Flyway will create the flyway_schema_history table
    envFromConfigmaps:
      DB_HOST: "common-public-catalog-data.DB_HOST"
      DB_PORT: "common-public-catalog-data.DB_PORT"
      DB_NAME: "common-public-catalog-data.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "public-catalog-data-flyway-user.username"
      FLYWAY_PASSWORD: "public-catalog-data-flyway-user.password"

  envFromConfigmaps:
    READMODEL_SQL_DB_HOST: "common-read-model.DB_HOST"
    READMODEL_SQL_DB_PORT: "common-read-model.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model.DB_USE_SSL"
    PUBLIC_CATALOG_DATA_SQL_DB_HOST: "common-public-catalog-data.DB_HOST"
    PUBLIC_CATALOG_DATA_SQL_DB_PORT: "common-public-catalog-data.DB_PORT"
    PUBLIC_CATALOG_DATA_SQL_DB_NAME: "common-public-catalog-data.DB_NAME"
    PUBLIC_CATALOG_DATA_SQL_DB_USE_SSL: "common-public-catalog-data.DB_USE_SSL"
    PUBLIC_CATALOG_SCHEMA_CATALOG: "common-public-catalog-data.DB_SCHEMA_CATALOG"
    PUBLIC_CATALOG_SCHEMA_ATTRIBUTE: "common-public-catalog-data.DB_SCHEMA_ATTRIBUTE"
    PUBLIC_CATALOG_SCHEMA_TENANT: "common-public-catalog-data.DB_SCHEMA_TENANT"

  envFromSecrets:
    READMODEL_SQL_DB_USERNAME: "platform-data-public-catalog-updater-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-public-catalog-updater-user.password"
    PUBLIC_CATALOG_DATA_SQL_DB_USERNAME: "public-catalog-data-public-catalog-updater-user.username"
    PUBLIC_CATALOG_DATA_SQL_DB_PASSWORD: "public-catalog-data-public-catalog-updater-user.password"
