name: "astro-frontend"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/" #TBD

service:
  create: true

configmap:

deployment:
  env:
  envFromConfigmaps:
    DB_HOST: "common-...DB_HOST"
    DB_NAME: "ccommon-...DB_NAME"
    DB_PORT: "common-...DB_PORT"
    DB_USE_SSL: "common-...DB_USE_SSL"
  envFromSecrets:
    DB_USERNAME: ""
    DB_PASSWORD: ""


    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"