apiVersion: v1
kind: ConfigMap
metadata:
  name: common-public-catalog-data
  namespace: dev-public-catalog
data:
  DB_HOST: "interop-public-catalog-data-dev.cluster-cevisn7oellx.eu-south-1.rds.amazonaws.com"
  DB_HOST_RO: "interop-public-catalog-data-dev.cluster-ro-cevisn7oellx.eu-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "dev_public_catalog"
  DB_USE_SSL: "true"
  DB_NAME_STRAPI: "dev_strapi"
  DB_SCHEMA_STRAPI: "strapi"
  DB_SCHEMA_CATALOG: "dev_catalog"
  DB_SCHEMA_ATTRIBUTE: "dev_attribute"
  DB_SCHEMA_TENANT: "dev_tenant"
