apiVersion: v1
kind: ConfigMap
metadata:
  name: common-public-catalog-data
  namespace: dev-public-catalog
data:
  DB_HOST: "interop-public-catalog-data-dev.cluster-cevisn7oellx.eu-south-1.rds.amazonaws.com"
  DB_HOST_RO: "interop-public-catalog-data-dev.cluster-ro-cevisn7oellx.eu-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "interop_public_catalog_data_dev"
  DB_USE_SSL: "true"
  DB_NAME_STRAPI: "strapi"
  DB_SCHEMA_STRAPI: "public" # TOCHECK
